### ISSUE TITLE
Konzept für Hilfsfunktionen

### ISSUE THREAD

**Issue by jan-christiansen** [hsfl-pltp/language-java#25]
Im Code tauchen Hilfsfunktionen auf, wie `\(VarDecl _ varid _) -> varid` und `identFromVarDeclId`. Diese sollten analog zu `jlint` einmal ein Module rausgezogen werden. Dazu muss ein Konzept erstellt werden, die die Module verwendet werden. Insbesondere kann der Ansatz aus `jlint` nicht direkt übertragen werden, da es dann zwei Module mit dem gleichen Namen gibt.

Anschließend können die Hilfsfunktionen, die in `language-java` bereits definiert sind, aus `jlint` entfernt werden.

**Comment by NiklasHargarter** [comment]
Umsetzung:
Für jeden Datentypen der Hilfsfunktionen benötigt wird im Verzeichnis Language/Java/Syntax ein Modul mit dem Namen des Datentyps angelegt.
Die Module werden qualifiziert importiert und die Methoden entsprechend benannt.
Es werden Hilfsfunktionen erstellt, die allgemein für den Datentyp gelten. 
Anwendungsspezifische Hilfsfunktionen verbleiben in der Anwendung in einem eigenen Modul.
