### ISSUE TITLE
Nicht-leere Listen

### ISSUE THREAD

**Issue by jan-christiansen** [hsfl-pltp/language-java#34]
Haskell stellt neben dem normalen Listen-Datentyp noch einen Datentyp für nicht-leere Listen (https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-List-NonEmpty.html) zur Verfügung. Bitte im AST einmal prüfen, ob es Stellen gibt, an denen aktuell eine Liste verwendet wird, die aber nie leer sein kann. Bitte an diesen Stellen `NonEmpty` statt der normalen Liste verwenden.

**Comment by mario-koehler** [comment]
Folgende Konstruktoren verwenden Listen, die immer mindestens ein Element beinhalten:
- ArrayIndex (Exp p) `[Exp p]`
- ArrayCreate Type `[Exp p]` Int
- NormalAnnotation [...] annKV :: `[(Ident, ElementValue p)]`
- FieldDecl SourceSpan [Modifier p] Type `[VarDecl p]`
- LocalVars SourceSpan [Modifier p] Type `[VarDecl p]`
- ForLocalVars [Modifier p] Type `[VarDecl p]`
- ForInitExps `[Exp p]`
- BasicFor SourceSpan (Maybe (ForInit p)) (Maybe (Exp p)) (Maybe `[Exp p]`) (Stmt p)
- ClassType `[(Ident, [TypeArgument])]`
- Name SourceSpan `[Ident]`
- SwitchCase `[Exp p]` (im Parser wird hier `seplist` statt `seplist1` verwendet - inkorrekt)
- SwitchExp (Exp p) `[SwitchExpBranch p]`
